# Generated by Django 2.1.1 on 2018-11-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-21 21:55:02.272504', max_length=255, unique=True),
        ),
    ]
