# Generated by Django 2.1.1 on 2018-10-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0002_auto_20181018_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-10-18 12:15:13.308041', max_length=255, unique=True),
        ),
    ]
