# Generated by Django 2.1.1 on 2018-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0002_auto_20181115_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-15 17:48:08.840943', max_length=255, unique=True),
        ),
    ]
