# Generated by Django 2.1.1 on 2018-11-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0002_auto_20181121_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-21 21:55:47.636072', max_length=255, unique=True),
        ),
    ]
