# Generated by Django 2.1.1 on 2018-10-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0004_auto_20181018_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-10-18 12:17:01.321013', max_length=255, unique=True),
        ),
    ]
