# Generated by Django 2.1.1 on 2018-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0004_auto_20181119_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-19 04:27:03.755486', max_length=255, unique=True),
        ),
    ]
