# Generated by Django 2.1.1 on 2018-10-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0011_auto_20181029_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-10-29 09:55:46.833602', max_length=255, unique=True),
        ),
    ]
