# Generated by Django 2.1.1 on 2018-10-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comunidades', '0012_auto_20181029_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-10-29 09:45:13.857348', max_length=255, unique=True),
        ),
    ]
