# Generated by Django 2.1.1 on 2018-11-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_auto_20181121_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeriaimagen',
            name='nombre',
            field=models.CharField(default='2018-11-22 22:42:47.149723', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-22 22:42:46.843015', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inicioimagen',
            name='nombre',
            field=models.CharField(default='2018-11-22 22:42:47.148612', max_length=255),
        ),
    ]
