# Generated by Django 2.1.1 on 2018-10-18 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comunidades', '0003_auto_20181018_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-18 12:15:13.323473', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('fechaInicio', models.DateField(default=datetime.datetime(2018, 10, 18, 17, 15, 13, 323473, tzinfo=utc))),
                ('fechaFin', models.DateField(default=datetime.datetime(2018, 11, 17, 17, 15, 13, 323473, tzinfo=utc))),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidades.Comunidad')),
                ('imagenes', models.ManyToManyField(to='Actividades.Imagen')),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
    ]
