# Generated by Django 2.1.1 on 2018-11-19 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0002_auto_20181115_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-19 03:35:40.473130', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2018, 12, 19, 3, 35, 40, 498852, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2018, 11, 19, 3, 35, 40, 474295, tzinfo=utc)),
        ),
    ]
