# Generated by Django 2.1.1 on 2018-10-26 17:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0003_auto_20181019_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-10-26 17:48:11.202429', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 17, 48, 11, 203334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2018, 10, 26, 17, 48, 11, 203290, tzinfo=utc)),
        ),
    ]
