# Generated by Django 2.1.1 on 2018-11-15 17:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comunidades', '0002_auto_20181115_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-11-15 17:29:47.296294', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_referencia', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('Fecha_de_Compra', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ordenes Pendientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('subCat', models.CharField(max_length=255)),
                ('communidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comunidades.Comunidad')),
                ('imagenes', models.ManyToManyField(to='Catalogo.Imagen')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
