# Generated by Django 2.1.1 on 2018-11-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-08 16:58:13.861144', max_length=255, unique=True),
        ),
    ]
