# Generated by Django 2.1.1 on 2018-11-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_auto_20181121_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-21 22:50:00.902839', max_length=255, unique=True),
        ),
    ]
