# Generated by Django 2.1.1 on 2018-11-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_auto_20181115_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-15 17:49:52.727991', max_length=255, unique=True),
        ),
    ]
