# Generated by Django 2.1.1 on 2018-11-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_auto_20181106_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-06 08:19:44.293180', max_length=255, unique=True),
        ),
    ]
