# Generated by Django 2.1.1 on 2018-11-19 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_auto_20181115_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='ordenes',
            name='monto_compra',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-19 03:35:40.252709', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='numero_referencia',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='productos',
            field=models.ManyToManyField(to='Catalogo.ProductosCheckout'),
        ),
    ]
