# Generated by Django 2.1.1 on 2018-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_auto_20181018_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-10-19 07:14:00.713559', max_length=255, unique=True),
        ),
    ]
