# Generated by Django 2.1.1 on 2018-11-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0004_auto_20181119_0336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoscheckout',
            options={'verbose_name_plural': 'ProductosCheckout'},
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='monto_compra',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='monto_totalcompra',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-11-19 04:27:03.980069', max_length=255, unique=True),
        ),
    ]
