# Generated by Django 2.1.1 on 2018-11-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Somos', '0002_auto_20181115_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='nombre',
            field=models.CharField(default='2018-11-19 03:35:40.508361', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2018-11-19 03:35:40.509834', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='somos',
            name='nombre',
            field=models.CharField(default='2018-11-19 03:35:40.507454', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='valor',
            name='nombre',
            field=models.CharField(default='2018-11-19 03:35:40.505557', max_length=255, unique=True),
        ),
    ]
