# Generated by Django 2.1.1 on 2018-10-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Somos', '0009_auto_20181029_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='nombre',
            field=models.CharField(default='2018-10-29 09:45:13.888597', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2018-10-29 09:45:13.888597', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='somos',
            name='nombre',
            field=models.CharField(default='2018-10-29 09:45:13.888597', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='valor',
            name='nombre',
            field=models.CharField(default='2018-10-29 09:45:13.888597', max_length=255, unique=True),
        ),
    ]
