# Generated by Django 2.1.1 on 2018-11-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colabora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-11-15 17:48:09.054357', max_length=255, unique=True),
        ),
    ]
