# Generated by Django 2.1.1 on 2018-11-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colabora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-11-06 08:19:44.295804', max_length=255, unique=True),
        ),
    ]
