# Generated by Django 2.1.1 on 2018-11-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colabora', '0002_auto_20181115_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-11-19 03:35:40.467977', max_length=255, unique=True),
        ),
    ]
