# Generated by Django 2.1.1 on 2018-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colabora', '0002_auto_20181018_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaboraimagen',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-10-19 07:14:00.717553', max_length=255, unique=True),
        ),
    ]
