# Generated by Django 2.1.1 on 2018-10-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Informacion de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
