# Generated by Django 2.1.1 on 2018-09-23 22:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-09-23 17:06:38.418934', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-09-23 17:06:38.376477', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='InicioImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('fechaFin', models.DateField(default=datetime.datetime(2018, 10, 23, 22, 6, 38, 416942, tzinfo=utc))),
                ('fechaInicio', models.DateField(default=datetime.datetime(2018, 9, 23, 22, 6, 38, 416942, tzinfo=utc))),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSCIAP.Comunidad')),
                ('imagenes', models.ManyToManyField(to='TSCIAP.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('communidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSCIAP.Comunidad')),
                ('imagenes', models.ManyToManyField(to='TSCIAP.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comunidad',
            name='imagenes',
            field=models.ManyToManyField(to='TSCIAP.Imagen'),
        ),
    ]
