# Generated by Django 2.1.1 on 2018-10-04 14:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Anuncios',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('empresa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='ColaboraImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.385811', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Imagenes de Colabora',
            },
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Informacion de Contacto',
            },
        ),
        migrations.CreateModel(
            name='GaleriaImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.385292', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Imagenes de Galeria',
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.350526', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Imagenes',
            },
        ),
        migrations.CreateModel(
            name='InicioImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.384761', max_length=255)),
                ('path', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Imagenes de Inicio',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.388203', max_length=255, unique=True)),
                ('mision', models.TextField()),
                ('imagen', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Misiones de Somos',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('fechaInicio', models.DateField(default=datetime.datetime(2018, 10, 4, 14, 33, 34, 382940, tzinfo=utc))),
                ('fechaFin', models.DateField(default=datetime.datetime(2018, 11, 3, 14, 33, 34, 382985, tzinfo=utc))),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSCIAP.Comunidad')),
                ('imagenes', models.ManyToManyField(to='TSCIAP.Imagen')),
            ],
            options={
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.386874', max_length=255, unique=True)),
                ('politica', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Politicas de Somos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('communidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSCIAP.Comunidad')),
                ('imagenes', models.ManyToManyField(to='TSCIAP.Imagen')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Somos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.387273', max_length=255, unique=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Titulos de Somos',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.386336', max_length=255, unique=True)),
                ('valor', models.TextField()),
                ('valoresImagen', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Valores de Somos',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='2018-10-04 14:33:34.387671', max_length=255, unique=True)),
                ('vision', models.TextField()),
                ('visionImagen', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Visiones de Somos',
            },
        ),
        migrations.AddField(
            model_name='comunidad',
            name='imagenes',
            field=models.ManyToManyField(to='TSCIAP.Imagen'),
        ),
    ]
