# Generated by Django 2.1.1 on 2018-09-27 03:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:16:21.599359', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='galeriaimagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:16:21.598863', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:16:21.563640', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inicioimagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:16:21.598366', max_length=255),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 3, 16, 21, 596832, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 27, 3, 16, 21, 596832, tzinfo=utc)),
        ),
    ]
