# Generated by Django 2.1.1 on 2018-09-23 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2018, 10, 23, 17, 29, 7, 245409, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2018, 9, 23, 17, 29, 7, 245409, tzinfo=utc)),
        ),
    ]
