# Generated by Django 2.1.1 on 2018-09-23 20:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2018-09-23 15:58:42.701015', max_length=255, unique=True)),
                ('path', models.ImageField(upload_to='galery')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='2018-09-23 15:58:42.658332', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2018, 10, 23, 20, 58, 42, 698004, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2018, 9, 23, 20, 58, 42, 698500, tzinfo=utc)),
        ),
    ]
