# Generated by Django 2.1.1 on 2018-10-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0002_auto_20180930_0009'),
        ('TSCIAP', '0002_auto_20180924_1850'),
    ]

    operations = [
    ]
