# Generated by Django 2.1.1 on 2018-09-23 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0002_auto_20180923_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryimage',
            name='name',
            field=models.CharField(default='2018-09-23 15:59:04.236771', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='2018-09-23 15:59:04.199034', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='endDate',
            field=models.DateField(default=datetime.datetime(2018, 10, 23, 20, 59, 4, 234747, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2018, 9, 23, 20, 59, 4, 234747, tzinfo=utc)),
        ),
    ]
