# Generated by Django 2.1.1 on 2018-09-27 03:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0002_auto_20180926_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:55:41.138038', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='galeriaimagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:55:41.138038', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:55:41.106780', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inicioimagen',
            name='nombre',
            field=models.CharField(default='2018-09-26 22:55:41.137538', max_length=255),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2018, 10, 27, 3, 55, 41, 136052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 27, 3, 55, 41, 136052, tzinfo=utc)),
        ),
    ]
