# Generated by Django 2.1.1 on 2018-09-30 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0003_auto_20180926_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Anuncios',
            },
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterModelOptions(
            name='colaboraimagen',
            options={'verbose_name_plural': 'Imagenes de Colabora'},
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name_plural': 'Comunidades'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name_plural': 'Informacion de Contacto'},
        ),
        migrations.AlterModelOptions(
            name='galeriaimagen',
            options={'verbose_name_plural': 'Imagenes de Galeria'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='inicioimagen',
            options={'verbose_name_plural': 'Imagenes de Inicio'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='mision',
            options={'verbose_name_plural': 'Misiones de Somos'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='politica',
            options={'verbose_name_plural': 'Politicas de Somos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='somos',
            options={'verbose_name_plural': 'Titulos de Somos'},
        ),
        migrations.AlterModelOptions(
            name='valor',
            options={'verbose_name_plural': 'Valores de Somos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterModelOptions(
            name='vision',
            options={'verbose_name_plural': 'Visiones de Somos'},
        ),
        migrations.AddField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.804546', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='politica',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.803551', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='somos',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.804047', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='valor',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.803551', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='vision',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.804047', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.803057', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='galeriaimagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.802561', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.772729', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inicioimagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:10:58.802561', max_length=255),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2018, 10, 30, 4, 10, 58, 801529, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 30, 4, 10, 58, 801529, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imagenes',
            field=models.ManyToManyField(to='TSCIAP.Imagen'),
        ),
    ]
