# Generated by Django 2.1.1 on 2018-09-30 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TSCIAP', '0004_auto_20180929_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboraimagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.891434', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='galeriaimagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.891434', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.860610', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='inicioimagen',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.890938', max_length=255),
        ),
        migrations.AlterField(
            model_name='mision',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.892922', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2018, 10, 30, 4, 29, 49, 889946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2018, 9, 30, 4, 29, 49, 889946, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='politica',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.891932', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='politica',
            name='politica',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='somos',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.892426', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='valor',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.891932', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vision',
            name='nombre',
            field=models.CharField(default='2018-09-29 23:29:49.892922', max_length=255, unique=True),
        ),
    ]
